services:
  - type: web
    name: api-infinitynet
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && tsc --skipLibCheck
    startCommand: npx prisma migrate deploy && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: mysql://u794012971_infinity_net:Infinity_net123@srv1434.hstgr.io:3306/u794012971_infinity_net
      - key: PORT
        value: 8080
      - key: API_KEY
        value: your_api_key_here
      - key: JWT_SECRET
        value: sua-chave-secreta-infinitynet-segura
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: CORS_ALLOWED_ORIGINS
        value: "*"